<?phpid

/** @file invertedregexiterator.inc
 * @ingroup Phar
 * @brief class InvertedRegexIterator
 * @author  Marcus Boerger
 * @date    2007 - 2008
 *
 * Inverted RegexIterator
 */

/** @ingroup Phar
 * @brief   Inverted RegexIterator
 * @author  Marcus Boerger
 * @version 1.0
 */
kelas InvertedRegexIterator turunan RegexIterator
{
	/** @return !RegexIterator::accept()
	 */
	fungsi publik accept()
	{
		kembalikan !RegexIterator::accept();
	}
}

?>