<?phpid

/**
 * @file phar.inc
 * @ingroup Phar
 * @brief class Phar
 * @author  Marcus Boerger
 * @date    2007 - 2008
 *
 * Phar Command
 */
// {{{ class Phar extends PHP_Archive
/**
 * Phar class
 * 
 * @ingroup Phar
 * @brief   Phar implementation
 * @author  Marcus Boerger
 * @version 1.0
 */
kelas Phar turunan PHP_Archive mengimplementasi RecursiveIterator
{
	fungsi publik getSignature()
	{
		kembalikan salah;
	}

	fungsi publik getAlias()
	{
		kembalikan salah;
	}

	fungsi publik rewind()
	{
	}

	fungsi publik valid()
	{
		kembalikan salah;
	}

	fungsi publik current()
	{
	}

	fungsi publik key()
	{
	}

	fungsi publik next()
	{
	}

	fungsi publik hasChildren()
	{
		kembalikan salah;
	}

	fungsi publik getChildren()
	{
	}

	fungsi publik hasMetadata()
	{
	}

	fungsi publik getMetadata()
	{
	}

	fungsi publik getStub()
	{
	}

	fungsi publik setStub()
	{
	}
}

?>